let newarray=[1,2,3,4,5];
let squaredArray=newarray.map((num)=>num*num);
console.log(squaredArray);
let evenNumbers=[1,2,3,4,5];
let filteredEvenNumbers=evenNumbers;
filteredEvenNumbers.filter(num=>num%2===0);
console.log(filteredEvenNumbers);
let sum=[1,2,3,4,5];
let total=sum.reduce((accumulator,currentValue)=>accumulator+currentValue,0);
console.log(total);